### ISSUE TITLE
Move G2IniParams.py from SDK to g2/python

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2updateproject#37]
*Editors note:*   Not 100% sure this is needed.

With the [Move G2IniParams.py from SDK to g2/python](https://github.com/Senzing/g2-python/issues/141), G2UpdateProject.py needs to handle G2IniParams differently

https://github.com/Senzing/g2updateproject/blob/4a8796f590dfac0f85af3a4d32fb23b708417bb0/G2UpdateProject.py#L71

Dependencies:

- https://github.com/Senzing/g2-python/issues/141

**Comment by jaeadams** [comment]
This is not needed after all.  Closing this, without changes.
